[package]
name = "warpBun"
version = "0.1.0"
edition = "2024"

[dependencies]
colog = "1.4.0"
log = "0.4.29"
regex = "1.12.2"
reqwest = { version = "0.12", features = ["blocking", "rustls-tls"] }
spinners = "4.1.1"
